// const gate2025da = [
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
//   {
//     id: 1,
//     type: "MCQ",
//     marks: 1,
//     negative: 0.33,
//     question: "",
//     options: ["9", "10", "11", "12"],
//     correct: ,
//     explanation: "",
//     subject: "Mathematics",
//   },
// ];


// export default gate2025da;